export interface Loesung {
  slug: string;
  name: string;
  keyword: string;
  metaTitle: string;
  metaDescription: string;
  heroTitle: string;
  heroSubtitle: string;
  svgPath: string;
  stats: { val: string; lbl: string }[];
  features: { icon: string; title: string; desc: string }[];
  useCases: { branche: string; example: string }[];
}

// Minimalistic SVG icons (stroke only, brand orange via CSS)
const icons = {
  chat: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>`,
  zap: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M13 2 3 14h9l-1 8 10-12h-9l1-8z"/></svg>`,
  headphones: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M3 18v-6a9 9 0 0 1 18 0v6"/><path d="M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3z"/><path d="M3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z"/></svg>`,
  barChart: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M3 3v18h18"/><path d="M18 17V9M12 17V5M6 17v-3"/></svg>`,
  edit: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M12 20h9"/><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z"/></svg>`,
  trendingUp: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="m22 7-8.5 8.5-5-5L2 17"/><path d="M16 7h6v6"/></svg>`,
  calculator: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="4" y="2" width="16" height="20" rx="2"/><line x1="8" y1="6" x2="16" y2="6"/><line x1="8" y1="10" x2="8" y2="10"/><line x1="12" y1="10" x2="12" y2="10"/><line x1="16" y1="10" x2="16" y2="10"/><line x1="8" y1="14" x2="8" y2="14"/><line x1="12" y1="14" x2="12" y2="14"/><line x1="16" y1="14" x2="16" y2="14"/><line x1="8" y1="18" x2="12" y2="18"/></svg>`,
  share: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg>`,
  search: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>`,
  mail: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>`,
  fileText: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>`,
  globe: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>`,
  image: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="18" height="18" rx="2"/><circle cx="8.5" cy="8.5" r="1.5"/><polyline points="21 15 16 10 5 21"/></svg>`,
  phone: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.62 1.1h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 8.73a16 16 0 0 0 6 6l.96-.96a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z"/></svg>`,
  workflow: `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round"><rect x="3" y="3" width="5" height="5" rx="1"/><rect x="16" y="3" width="5" height="5" rx="1"/><rect x="16" y="16" width="5" height="5" rx="1"/><rect x="3" y="16" width="5" height="5" rx="1"/><path d="M8 5.5h8M18.5 8v8M16 18.5H8M5.5 16V8"/></svg>`,
};

export const LOESUNGEN: Loesung[] = [
  {
    slug: "ki-chatbot-unternehmen",
    name: "KI Chatbot",
    keyword: "KI Chatbot für Unternehmen",
    metaTitle: "KI Chatbot für Unternehmen erstellen | kiberatung.de",
    metaDescription: "KI-Chatbot für Ihr Unternehmen: 24/7 Kundensupport, Lead-Qualifizierung und interne Wissensdatenbank. Kostenlose Erstberatung.",
    heroTitle: "KI CHATBOT FÜR UNTERNEHMEN",
    heroSubtitle: "Kunden wollen sofortige Antworten — rund um die Uhr. Ein KI-Chatbot beantwortet Anfragen in Sekunden, qualifiziert Leads automatisch und entlastet Ihr Team dauerhaft.",
    svgPath: "M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z",
    stats: [{ val: "24/7", lbl: "Verfügbarkeit" }, { val: "−65%", lbl: "Support-Tickets" }, { val: "<2s", lbl: "Antwortzeit" }],
    features: [
      { icon: icons.chat, title: "Kundensupport rund um die Uhr", desc: "Beantwortet FAQs, Bestellstatus, Rücksendungen — ohne Wartezeit und ohne Nachtschicht." },
      { icon: icons.trendingUp, title: "Lead-Qualifizierung", desc: "Chatbot erfasst Kontaktdaten, stellt Qualifizierungsfragen und übergibt heiße Leads direkt ans Vertriebsteam." },
      { icon: icons.fileText, title: "Interne Wissensdatenbank", desc: "Mitarbeiter fragen den Bot statt Kollegen zu unterbrechen — HR-Richtlinien, Prozessdokus, Produktinfos auf Knopfdruck." },
      { icon: icons.globe, title: "Mehrsprachig & omnichannel", desc: "Ein Bot für Website, WhatsApp, Teams und mehr — in Deutsch, Englisch und 30+ Sprachen." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Bestellstatus, Retouren und Produktfragen automatisch bearbeiten" },
      { branche: "Gastronomie", example: "Reservierungen, Speisekartenanfragen und Öffnungszeiten" },
      { branche: "Gesundheitswesen", example: "Terminbuchung, Symptomcheck und FAQ für Patienten" },
      { branche: "Finanzbranche", example: "Kontoinfos, Produktberatung und Dokumentenanfragen" },
    ],
  },
  {
    slug: "ki-prozessautomatisierung",
    name: "Prozessautomatisierung",
    keyword: "KI Automatisierung",
    metaTitle: "KI Prozessautomatisierung für Unternehmen | kiberatung.de",
    metaDescription: "Mit KI Prozesse automatisieren: Datenerfassung, Genehmigungen, Berichte — ohne Programmierung. ROI in Wochen statt Jahren.",
    heroTitle: "KI PROZESSAUTOMATISIERUNG",
    heroSubtitle: "Manuelle Routineaufgaben kosten Ihr Team täglich Stunden. KI übernimmt Datenerfassung, Genehmigungsprozesse und Reporting — schneller, günstiger und fehlerfrei.",
    svgPath: "M13 2 3 14h9l-1 8 10-12h-9l1-8z",
    stats: [{ val: "+40%", lbl: "Produktivität" }, { val: "−80%", lbl: "manuelle Dateneingabe" }, { val: "ROI", lbl: "in 6–12 Wochen" }],
    features: [
      { icon: icons.workflow, title: "Workflow-Automatisierung", desc: "Dokumente erfassen, validieren, weiterleiten — vollautomatisch ohne manuellen Eingriff." },
      { icon: icons.fileText, title: "Intelligente Dokumentenverarbeitung", desc: "Rechnungen, Verträge und Formulare werden per KI ausgelesen, klassifiziert und ins ERP übertragen." },
      { icon: icons.barChart, title: "Automatisches Reporting", desc: "KI zieht täglich Daten aus allen Systemen und erstellt fertige Berichte — ohne manuellen Aufwand." },
      { icon: icons.zap, title: "Genehmigungsprozesse", desc: "Urlaubsanträge, Freigaben, Bestellgenehmigungen — automatisch geroutet, nachverfolgt und eskaliert." },
    ],
    useCases: [
      { branche: "Mittelstand", example: "Eingangsrechnungen automatisch buchen und freigeben" },
      { branche: "Logistik", example: "Lieferscheine und Zolldokumente automatisch erstellen" },
      { branche: "Handwerk", example: "Angebote, Auftragsbestätigungen und Rechnungen automatisieren" },
      { branche: "Steuerberater", example: "Belegerfassung und DATEV-Übergabe ohne manuelle Eingabe" },
    ],
  },
  {
    slug: "ki-kundenservice",
    name: "KI Kundenservice",
    keyword: "KI im Kundenservice",
    metaTitle: "KI im Kundenservice | kiberatung.de",
    metaDescription: "KI-gestützter Kundenservice: schnellere Bearbeitung, höhere Zufriedenheit, weniger Kosten. Omnichannel — E-Mail, Chat, Telefon.",
    heroTitle: "KI IM KUNDENSERVICE",
    heroSubtitle: "Kunden erwarten schnelle Antworten auf jedem Kanal. KI bearbeitet Anfragen automatisch, priorisiert Tickets und gibt Agenten Echtzeit-Unterstützung — bei gleichem oder kleinerem Team.",
    svgPath: "M3 18v-6a9 9 0 0 1 18 0v6M21 19a2 2 0 0 1-2 2h-1a2 2 0 0 1-2-2v-3a2 2 0 0 1 2-2h3zM3 19a2 2 0 0 0 2 2h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2H3z",
    stats: [{ val: "−50%", lbl: "Bearbeitungszeit" }, { val: "+30%", lbl: "Kundenzufriedenheit" }, { val: "80%", lbl: "Auto-Lösungsrate" }],
    features: [
      { icon: icons.headphones, title: "Ticket-Triage & Priorisierung", desc: "KI liest jede Anfrage, erkennt Dringlichkeit und Kategorie und routet automatisch zum richtigen Agenten." },
      { icon: icons.chat, title: "Agenten-Assistent in Echtzeit", desc: "Schlägt Antworten vor, ruft Kundendaten ab und zeigt passende Wissensdatenbank-Artikel — während der Agent tippt." },
      { icon: icons.mail, title: "E-Mail-Automatisierung", desc: "Standardanfragen werden automatisch beantwortet. Komplexe Fälle landen beim richtigen Mitarbeiter — mit KI-Vorschlag." },
      { icon: icons.barChart, title: "Service-Analytics", desc: "Welche Themen häufen sich? Wo gibt es Engpässe? KI-Dashboards zeigen Handlungsbedarf sofort." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Retouren, Bestellstatus, Produktfragen automatisch lösen" },
      { branche: "Versicherungen", example: "Schadenmeldungen vorqualifizieren und routen" },
      { branche: "Telekommunikation", example: "Störungsmeldungen automatisch triagieren" },
      { branche: "SaaS", example: "Technischen Support mit KI-Wissensdatenbank unterstützen" },
    ],
  },
  {
    slug: "ki-datenanalyse",
    name: "KI Datenanalyse",
    keyword: "KI Datenanalyse",
    metaTitle: "KI Datenanalyse für Unternehmen | kiberatung.de",
    metaDescription: "Daten mit KI auswerten: Muster erkennen, Prognosen erstellen, Entscheidungen beschleunigen. Für jede Datenmenge und jedes Format.",
    heroTitle: "KI DATENANALYSE",
    heroSubtitle: "In Ihren Daten stecken Antworten auf Ihre wichtigsten Fragen. KI findet Muster, erstellt Prognosen und liefert Handlungsempfehlungen — in Minuten statt Wochen.",
    svgPath: "M3 3v18h18M18 17V9M12 17V5M6 17v-3",
    stats: [{ val: "3×", lbl: "schnellere Entscheidungen" }, { val: "−90%", lbl: "Analyseaufwand" }, { val: "Live", lbl: "Echtzeit-Insights" }],
    features: [
      { icon: icons.barChart, title: "Predictive Analytics", desc: "KI prognostiziert Umsatz, Nachfrage, Ausfälle und Kundenabwanderung — auf Basis historischer Daten." },
      { icon: icons.search, title: "Anomalie-Erkennung", desc: "Ungewöhnliche Muster in Finanzdaten, Produktionsdaten oder Kundendaten werden automatisch gemeldet." },
      { icon: icons.fileText, title: "Automatisches Reporting", desc: "KI erstellt täglich, wöchentlich oder monatlich fertige Berichte mit Visualisierungen — für jede Zielgruppe." },
      { icon: icons.workflow, title: "Daten-Integration", desc: "ERP, CRM, Excel, Datenbanken — KI verbindet alle Quellen zu einem konsistenten Analyse-Layer." },
    ],
    useCases: [
      { branche: "Einzelhandel", example: "Verkaufsprognosen und Bestandsoptimierung" },
      { branche: "Produktion", example: "Qualitätsmuster und Maschinendaten analysieren" },
      { branche: "Finanzbranche", example: "Risikomodelle und Portfolio-Analysen" },
      { branche: "Logistik", example: "Routenoptimierung und Lastprognosen" },
    ],
  },
  {
    slug: "ki-content-erstellung",
    name: "KI Content",
    keyword: "KI Content erstellen",
    metaTitle: "KI Content erstellen für Unternehmen | kiberatung.de",
    metaDescription: "Mit KI Texte, Bilder und Marketing-Content erstellen: Produktbeschreibungen, Blogartikel, Social Posts — im Markenton, skalierbar.",
    heroTitle: "KI CONTENT ERSTELLUNG",
    heroSubtitle: "Content-Hunger kostet Zeit und Geld. KI schreibt Produkttexte, Blogartikel, Social Posts und E-Mails in Ihrem Markenton — schneller als jede Agentur.",
    svgPath: "M12 20h9M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z",
    stats: [{ val: "10×", lbl: "mehr Content-Output" }, { val: "−70%", lbl: "Textkosten" }, { val: "SEO", lbl: "direkt optimiert" }],
    features: [
      { icon: icons.edit, title: "Produktbeschreibungen im Scale", desc: "Hunderte SEO-optimierte Produkttexte auf einmal — im Stil Ihrer Marke, mit Keyword-Targeting." },
      { icon: icons.fileText, title: "Blogartikel & Ratgeber", desc: "KI recherchiert, strukturiert und schreibt Long-Form-Content mit echtem Mehrwert — fertig zur Freigabe." },
      { icon: icons.share, title: "Social Media Content", desc: "LinkedIn-Posts, Instagram-Captions, Twitter-Threads — täglich, konsistent und plattformgerecht." },
      { icon: icons.mail, title: "E-Mail-Kampagnen", desc: "Personalisierte E-Mail-Sequenzen für jeden Funnel-Schritt — von Willkommensmail bis Re-Engagement." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Tausende Produktbeschreibungen automatisch generieren" },
      { branche: "Marketing-Agenturen", example: "Content für mehrere Kunden parallel produzieren" },
      { branche: "Medien & Verlage", example: "Nachrichtenartikel, Zusammenfassungen und Newsletter" },
      { branche: "Immobilien", example: "Exposé-Texte aus Fotos und Eckdaten erstellen" },
    ],
  },
  {
    slug: "ki-vertrieb",
    name: "KI Vertrieb",
    keyword: "KI im Vertrieb",
    metaTitle: "KI im Vertrieb | AI Sales Automation | kiberatung.de",
    metaDescription: "Mit KI mehr Umsatz: Lead-Scoring, automatisierte Follow-ups, KI-Angebotserstellung. Für B2B- und B2C-Vertriebsteams.",
    heroTitle: "KI IM VERTRIEB",
    heroSubtitle: "Vertrieb ist Zeitaufwand. KI identifiziert die besten Leads, erstellt Angebote und schreibt Follow-up-E-Mails — damit Ihre Verkäufer verkaufen statt verwalten.",
    svgPath: "m22 7-8.5 8.5-5-5L2 17M16 7h6v6",
    stats: [{ val: "+25%", lbl: "Abschlussrate" }, { val: "−60%", lbl: "Administrationsaufwand" }, { val: "3×", lbl: "mehr qualifizierte Leads" }],
    features: [
      { icon: icons.trendingUp, title: "Lead-Scoring", desc: "KI bewertet jeden Lead nach Kaufwahrscheinlichkeit — Vertrieb fokussiert auf die Top 20% mit 80% Abschlusspotenzial." },
      { icon: icons.mail, title: "Automatisierte Follow-ups", desc: "KI-Sequenzen halten den Kontakt warm — mit personalisierten E-Mails zum richtigen Zeitpunkt." },
      { icon: icons.fileText, title: "KI-Angebotserstellung", desc: "Auf Basis von CRM-Daten erstellt KI individuelle Angebote in Minuten — formatiert und kalkuliert." },
      { icon: icons.barChart, title: "Sales-Forecasting", desc: "KI prognostiziert Quartalsumsätze auf Basis von Pipeline, Saison und historischen Daten." },
    ],
    useCases: [
      { branche: "Mittelstand", example: "B2B-Leads priorisieren und Angebotsprozess beschleunigen" },
      { branche: "Immobilien", example: "Interessenten automatisch qualifizieren und nachfassen" },
      { branche: "Versicherungen", example: "Cross-Selling-Potenziale erkennen und automatisch ansprechen" },
      { branche: "SaaS", example: "Trial-User in zahlende Kunden konvertieren" },
    ],
  },
  {
    slug: "ki-buchhaltung",
    name: "KI Buchhaltung",
    keyword: "KI Buchhaltung",
    metaTitle: "KI Buchhaltung & Rechnungswesen | kiberatung.de",
    metaDescription: "Buchhaltung mit KI: automatische Belegerfassung, Buchungssätze, Kontenabstimmung — DATEV-kompatibel und DSGVO-konform.",
    heroTitle: "KI IN DER BUCHHALTUNG",
    heroSubtitle: "Belegstapel, manuelle Buchungen, Monatsabschlüsse. KI übernimmt die Routinearbeit in der Buchhaltung — schneller, genauer und DATEV-kompatibel.",
    svgPath: "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M16 13H8M16 17H8M10 9H8",
    stats: [{ val: "−70%", lbl: "Erfassungsaufwand" }, { val: "99%", lbl: "Erkennungsrate" }, { val: "0", lbl: "verpasste Fristen" }],
    features: [
      { icon: icons.fileText, title: "Automatische Belegerfassung", desc: "OCR + KI liest Rechnungen, Quittungen und Kontoauszüge — und bucht sie direkt ins System." },
      { icon: icons.calculator, title: "Intelligente Buchungssätze", desc: "KI erkennt Kontext und Kategorie jedes Belegs und schlägt den richtigen Buchungssatz vor." },
      { icon: icons.barChart, title: "Kontenabstimmung", desc: "Automatischer Abgleich von Bankkonten, Kreditkarten und Buchhaltung — inklusive Differenz-Meldungen." },
      { icon: icons.workflow, title: "DATEV & ERP-Integration", desc: "Nahtlose Übergabe an DATEV, SAP, Lexoffice und andere Systeme — ohne manuelle Nacharbeit." },
    ],
    useCases: [
      { branche: "Steuerberater", example: "Mandantenbuchhaltung automatisieren und Fristen einhalten" },
      { branche: "Mittelstand", example: "Creditor- und Debitoren-Buchhaltung ohne Vollzeitkraft" },
      { branche: "Handwerk", example: "Eingangsrechnungen und Ausgangsrechnungen ohne Papier" },
      { branche: "Gastronomie", example: "Tages- und Wochenabrechnungen automatisch erstellen" },
    ],
  },
  {
    slug: "ki-social-media",
    name: "KI Social Media",
    keyword: "KI Social Media",
    metaTitle: "KI Social Media Marketing | kiberatung.de",
    metaDescription: "Mit KI Social Media automatisieren: Posts erstellen, planen und analysieren — für LinkedIn, Instagram, Facebook und mehr.",
    heroTitle: "KI FÜR SOCIAL MEDIA",
    heroSubtitle: "Täglich posten, auf allen Kanälen, mit konsistenter Markenstimme. KI erstellt Ihren Content-Kalender, schreibt Posts und analysiert was funktioniert.",
    svgPath: "M17 2H7a5 5 0 0 0-5 5v10a5 5 0 0 0 5 5h10a5 5 0 0 0 5-5V7a5 5 0 0 0-5-5zM16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37zM17.5 6.5h.01",
    stats: [{ val: "×5", lbl: "mehr Posts ohne Mehraufwand" }, { val: "+40%", lbl: "Reichweite" }, { val: "−80%", lbl: "Zeitaufwand" }],
    features: [
      { icon: icons.edit, title: "Content-Generierung", desc: "KI schreibt Posts für LinkedIn, Instagram, Facebook und TikTok — plattformgerecht und im Markentons." },
      { icon: icons.workflow, title: "Automatisches Publishing", desc: "Content-Kalender füllen, Beiträge terminieren und automatisch veröffentlichen — kein manuelles Eingreifen." },
      { icon: icons.barChart, title: "Performance-Analyse", desc: "Welche Posts funktionieren? KI analysiert Reichweite, Engagement und Conversions und optimiert die Strategie." },
      { icon: icons.chat, title: "Community Management", desc: "KI antwortet auf Kommentare und DMs automatisch — eskaliert nur komplexe oder sensible Anfragen." },
    ],
    useCases: [
      { branche: "Marketing-Agenturen", example: "Social Content für mehrere Kunden gleichzeitig produzieren" },
      { branche: "Einzelhandel", example: "Produktneuheiten und Aktionen automatisch bewerben" },
      { branche: "Gastronomie", example: "Tagesgerichte, Events und Bewertungen teilen" },
      { branche: "Immobilien", example: "Neue Objekte auf allen Kanälen automatisch publizieren" },
    ],
  },
  {
    slug: "ki-seo",
    name: "KI SEO",
    keyword: "KI SEO",
    metaTitle: "KI SEO — Suchmaschinenoptimierung mit KI | kiberatung.de",
    metaDescription: "SEO mit KI: automatische Content-Erstellung, Keyword-Analyse und technisches SEO-Monitoring. Mehr organischer Traffic ohne Agentur.",
    heroTitle: "SEO MIT KI",
    heroSubtitle: "Google dominieren ohne Agenturbudget. KI analysiert Keywords, erstellt SEO-optimierten Content und überwacht Rankings — automatisch und kontinuierlich.",
    svgPath: "M11 17a6 6 0 1 0 0-12 6 6 0 0 0 0 12zM21 21l-4.35-4.35",
    stats: [{ val: "+120%", lbl: "organischer Traffic" }, { val: "10×", lbl: "mehr SEO-Content" }, { val: "−60%", lbl: "Kosten vs. Agentur" }],
    features: [
      { icon: icons.search, title: "Keyword-Recherche & Cluster", desc: "KI findet profitable Keywords mit niedrigem Wettbewerb und clustert sie in sinnvolle Content-Gruppen." },
      { icon: icons.edit, title: "SEO-Content-Generierung", desc: "Blogartikel, Landingpages und Produkttexte — KI schreibt vollständigen SEO-Content direkt." },
      { icon: icons.barChart, title: "Ranking-Monitoring", desc: "Automatisches Tracking aller Keywords, Wettbewerber und Core-Web-Vitals — mit wöchentlichem Report." },
      { icon: icons.workflow, title: "Technisches SEO-Audit", desc: "KI crawlt Ihre Website, findet technische Fehler und priorisiert Fixes nach Impact." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Tausende Kategorie- und Produktseiten optimieren" },
      { branche: "Dienstleistungen", example: "Lokales SEO für mehrere Standorte" },
      { branche: "Medien & Verlage", example: "Artikel-Content für Top-Rankings erstellen" },
      { branche: "SaaS", example: "Bottom-of-Funnel Content für Purchase-Intent Keywords" },
    ],
  },
  {
    slug: "ki-email-marketing",
    name: "KI E-Mail Marketing",
    keyword: "KI E-Mail Marketing",
    metaTitle: "KI E-Mail Marketing Automation | kiberatung.de",
    metaDescription: "E-Mail Marketing mit KI: personalisierte Kampagnen, automatische Segmentierung und Betreff-Optimierung — für höhere Öffnungsraten.",
    heroTitle: "KI E-MAIL MARKETING",
    heroSubtitle: "Generische Newsletter funktionieren nicht mehr. KI personalisiert jede E-Mail, wählt den optimalen Versandzeitpunkt und steigert Ihre Öffnungsraten messbar.",
    svgPath: "M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2zM22 6l-10 7L2 6",
    stats: [{ val: "+45%", lbl: "Öffnungsrate" }, { val: "+28%", lbl: "Click-Through-Rate" }, { val: "×3", lbl: "Conversion vs. Broadcast" }],
    features: [
      { icon: icons.mail, title: "Personalisierte Kampagnen", desc: "Jeder Empfänger bekommt Betreff, Inhalt und CTA basierend auf Verhalten und Präferenzen — dynamisch generiert." },
      { icon: icons.workflow, title: "Automatische Segmentierung", desc: "KI teilt Ihre Liste in verhaltensbasierte Segmente — und spricht jeden Cluster anders an." },
      { icon: icons.trendingUp, title: "Betreff-Optimierung", desc: "KI testet Betreffzeilen automatisch und lernt was bei Ihrer Zielgruppe funktioniert." },
      { icon: icons.barChart, title: "Kampagnen-Analytics", desc: "Öffnungsraten, Klicks, Conversions und Abmeldungen — mit KI-Empfehlungen zur Optimierung." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Abandoned-Cart, Re-Engagement und Upsell-Sequenzen" },
      { branche: "Einzelhandel", example: "Aktions- und Saisonkampagnen automatisch personalisieren" },
      { branche: "Marketing-Agenturen", example: "Kampagnen für mehrere Kunden parallel betreiben" },
      { branche: "SaaS", example: "Trial-Nurturing und Upgrade-E-Mail-Sequenzen" },
    ],
  },
  {
    slug: "ki-dokumentenanalyse",
    name: "KI Dokumentenanalyse",
    keyword: "KI Dokumente analysieren",
    metaTitle: "KI Dokumentenanalyse | Verträge & Dokumente per KI | kiberatung.de",
    metaDescription: "Dokumente per KI analysieren: Verträge prüfen, Daten extrahieren, Berichte zusammenfassen — in Sekunden statt Stunden.",
    heroTitle: "KI DOKUMENTENANALYSE",
    heroSubtitle: "Hunderte Seiten Verträge, Berichte und Akten. KI liest, versteht und extrahiert in Sekunden was relevant ist — und erstellt strukturierte Zusammenfassungen.",
    svgPath: "M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8zM14 2v6h6M16 13H8M16 17H8M10 9H8",
    stats: [{ val: "−90%", lbl: "Lesezeit" }, { val: "99%", lbl: "Extraktionsgenauigkeit" }, { val: "Sek.", lbl: "statt Stunden" }],
    features: [
      { icon: icons.fileText, title: "Vertragsanalyse", desc: "KI erkennt Risikoclauseln, Fristen und Abweichungen vom Standard — in jedem Vertragstyp." },
      { icon: icons.search, title: "Intelligente Suche", desc: "Fragen stellen statt suchen: 'Welche Verträge laufen bis März aus?' — KI findet die Antwort sofort." },
      { icon: icons.workflow, title: "Datenextraktion", desc: "Namen, Daten, Beträge und Klauseln strukturiert aus PDFs, Scans und Word-Dokumenten extrahieren." },
      { icon: icons.edit, title: "Automatische Zusammenfassungen", desc: "100-Seiten-Berichte in 5-Sätze-Executive-Summary — KI destilliert das Wesentliche." },
    ],
    useCases: [
      { branche: "Rechtsanwälte", example: "Vertragsrisiken und Fristen automatisch identifizieren" },
      { branche: "Finanzbranche", example: "Geschäftsberichte und Due-Diligence-Dokumente analysieren" },
      { branche: "Versicherungen", example: "Schadenmeldungen und Police-Dokumente auslesen" },
      { branche: "Immobilien", example: "Mietverträge, Grundbuchauszüge und Gutachten verarbeiten" },
    ],
  },
  {
    slug: "ki-uebersetzung",
    name: "KI Übersetzung",
    keyword: "KI Übersetzer Business",
    metaTitle: "KI Übersetzung für Unternehmen | kiberatung.de",
    metaDescription: "Professionelle KI-Übersetzungen für Unternehmen: Dokumente, Websites und Marketing-Content — schnell, günstig und markenkonform.",
    heroTitle: "KI ÜBERSETZUNG FÜR UNTERNEHMEN",
    heroSubtitle: "Übersetzer kosten Zeit und Geld. KI liefert marktreife Übersetzungen in 50+ Sprachen — für Dokumente, Websites und Marketing-Content, in Ihrem Markenton.",
    svgPath: "M3 5h12M9 3v2m1.048 9.5A18.022 18.022 0 0 1 6.412 9m6.088 9h7M11 21l5-10 5 10M12.751 5C11.783 10.77 8.07 15.61 3 18.129",
    stats: [{ val: "50+", lbl: "Sprachen" }, { val: "−85%", lbl: "Übersetzungskosten" }, { val: "Minuten", lbl: "statt Tage" }],
    features: [
      { icon: icons.globe, title: "Dokument-Übersetzung", desc: "PDFs, Word-Dokumente, Präsentationen — KI übersetzt und behält Formatierung und Layout." },
      { icon: icons.workflow, title: "Website-Lokalisierung", desc: "Komplette Websites in mehrere Sprachen übersetzen und kulturell anpassen." },
      { icon: icons.edit, title: "Marken-konforme Übersetzung", desc: "KI lernt Ihren Markenton und wendet ihn konsistent in allen Sprachen an." },
      { icon: icons.barChart, title: "Translation Memory", desc: "Bereits übersetzte Passagen werden wiederverwendet — Kosten sinken mit jedem Projekt." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Produktkataloge und Shops für internationale Märkte" },
      { branche: "Tourismus & Hotels", example: "Gästekommunikation und Speisekarten mehrsprachig" },
      { branche: "Gastronomie", example: "Speisekarten automatisch übersetzen und aktuell halten" },
      { branche: "Logistik", example: "Zolldokumente und Lieferscheine automatisch übersetzen" },
    ],
  },
  {
    slug: "ki-bildgenerierung",
    name: "KI Bildgenerierung",
    keyword: "KI Bilder erstellen",
    metaTitle: "KI Bildgenerierung für Unternehmen | kiberatung.de",
    metaDescription: "Mit KI Bilder erstellen: Produktfotos, Illustrationen, Marketing-Visuals — ohne Fotoshooting, sofort und kostengünstig.",
    heroTitle: "KI BILDGENERIERUNG",
    heroSubtitle: "Hochwertige Visuals ohne Fotoshooting. KI erstellt Produktbilder, Marketing-Grafiken und Illustrationen auf Knopfdruck — in Ihrem Stil, in Minuten.",
    svgPath: "M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z",
    stats: [{ val: "−90%", lbl: "Bildproduktionskosten" }, { val: "Minuten", lbl: "statt Wochen" }, { val: "∞", lbl: "Variationen" }],
    features: [
      { icon: icons.image, title: "Produktfotografie", desc: "KI generiert professionelle Produktbilder in verschiedenen Settings — ohne Studio und Fotograf." },
      { icon: icons.edit, title: "Marketing-Visuals", desc: "Social-Media-Grafiken, Banner und Werbemittel im Markenstil — konsistent und skalierbar." },
      { icon: icons.workflow, title: "Bildvariationen & A/B-Tests", desc: "Unbegrenzte Variationen eines Motivs für A/B-Tests — in Sekunden statt Tagen." },
      { icon: icons.search, title: "Stil-Konsistenz", desc: "KI lernt Ihren visuellen Stil und reproduziert ihn zuverlässig in jedem neuen Bild." },
    ],
    useCases: [
      { branche: "E-Commerce", example: "Produktfotos in verschiedenen Farben und Settings" },
      { branche: "Marketing-Agenturen", example: "Kampagnen-Visuals schnell und günstig produzieren" },
      { branche: "Gastronomie", example: "Gerichte für Speisekarte und Social Media bildlich darstellen" },
      { branche: "Immobilien", example: "Virtual Staging — leere Räume möbliert darstellen" },
    ],
  },
  {
    slug: "ki-voicebot",
    name: "KI Voicebot",
    keyword: "KI Telefonassistent",
    metaTitle: "KI Voicebot & Telefonassistent | kiberatung.de",
    metaDescription: "KI-Telefonassistent: eingehende Anrufe automatisch bearbeiten, Termine buchen, Informationen geben — ohne Warteschleife.",
    heroTitle: "KI VOICEBOT & TELEFONASSISTENT",
    heroSubtitle: "Jeder Anruf kostet Zeit. Ein KI-Telefonassistent nimmt Anrufe entgegen, beantwortet Fragen, bucht Termine und gibt Informationen — in natürlicher Sprache, rund um die Uhr.",
    svgPath: "M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12a19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 3.62 1.1h3a2 2 0 0 1 2 1.72c.127.96.361 1.903.7 2.81a2 2 0 0 1-.45 2.11L7.91 8.73a16 16 0 0 0 6 6l.96-.96a2 2 0 0 1 2.11-.45c.907.339 1.85.573 2.81.7A2 2 0 0 1 22 16.92z",
    stats: [{ val: "24/7", lbl: "Erreichbarkeit" }, { val: "−70%", lbl: "Anrufaufwand" }, { val: "<3s", lbl: "Reaktionszeit" }],
    features: [
      { icon: icons.phone, title: "Eingehende Anrufe", desc: "KI nimmt Anrufe entgegen, versteht das Anliegen und bearbeitet es direkt — oder verbindet gezielt weiter." },
      { icon: icons.workflow, title: "Terminbuchung per Telefon", desc: "Kalenderintegration in Echtzeit — Termine buchen, verschieben und bestätigen ohne menschliche Hilfe." },
      { icon: icons.chat, title: "Natürliche Sprache", desc: "Kein Sprachmenü, keine Nummern drücken — freie Konversation in natürlichem Deutsch." },
      { icon: icons.barChart, title: "Anruf-Analytics", desc: "Welche Anliegen kommen am häufigsten? Zu welchen Zeiten? KI liefert vollständige Auswertungen." },
    ],
    useCases: [
      { branche: "Handwerk", example: "Anrufannahme und Terminbuchung auf der Baustelle" },
      { branche: "Gesundheitswesen", example: "Terminvereinbarungen und Rückrufbitten automatisch bearbeiten" },
      { branche: "Gastronomie", example: "Reservierungsanfragen und Öffnungszeiten telefonisch bearbeiten" },
      { branche: "Logistik", example: "Lieferstatus-Anfragen automatisch beantworten" },
    ],
  },
  {
    slug: "ki-workflow-automatisierung",
    name: "KI Workflow Automatisierung",
    keyword: "KI Workflow",
    metaTitle: "KI Workflow Automatisierung mit n8n | kiberatung.de",
    metaDescription: "Workflows mit KI automatisieren: n8n, Make, Zapier — verbunden mit ChatGPT, Claude und Ihren Systemen. Komplexe Abläufe ohne Programmierung.",
    heroTitle: "KI WORKFLOW AUTOMATISIERUNG",
    heroSubtitle: "Systeme reden nicht miteinander, Daten stecken in Silos, manuelle Übergaben kosten Stunden. KI-Workflows verbinden alles — und lassen Prozesse automatisch laufen.",
    svgPath: "M3 3h5v5H3zM16 3h5v5h-5zM3 16h5v5H3zM16 16h5v5h-5zM8 5.5h8M18.5 8v8M16 18.5H8M5.5 16V8",
    stats: [{ val: "−85%", lbl: "manuelle Übergaben" }, { val: "24/7", lbl: "vollautomatisch" }, { val: "Tage", lbl: "bis zum ersten Workflow" }],
    features: [
      { icon: icons.workflow, title: "System-Integration", desc: "CRM, ERP, E-Mail, Slack, Kalender — KI-Workflows verbinden alle Tools ohne eigene API-Entwicklung." },
      { icon: icons.zap, title: "Trigger-basierte Automation", desc: "Eingehende E-Mail → Daten extrahieren → CRM aktualisieren → Aufgabe anlegen → Benachrichtigung senden." },
      { icon: icons.barChart, title: "n8n & Make Implementierung", desc: "Wir bauen Ihre Workflows in n8n oder Make — inklusive KI-Nodes für ChatGPT, Claude und mehr." },
      { icon: icons.search, title: "Monitoring & Fehlerbehandlung", desc: "Automatische Überwachung, Fehler-Alerts und Fallback-Logik — Workflows laufen zuverlässig." },
    ],
    useCases: [
      { branche: "Marketing-Agenturen", example: "Lead-zu-Kunde-Workflow vollautomatisch abbilden" },
      { branche: "E-Commerce", example: "Bestellung → Lager → Versand → Kundenkommunikation" },
      { branche: "Mittelstand", example: "HR-Onboarding von Anmeldung bis Systemzugang automatisieren" },
      { branche: "Dienstleistungen", example: "Kundenanfrage → Angebot → Vertrag → Projektanlage" },
    ],
  },
];

export function getLoesungBySlug(slug: string): Loesung | undefined {
  return LOESUNGEN.find((l) => l.slug === slug);
}

export function getAllLoesungenSlugs(): string[] {
  return LOESUNGEN.map((l) => l.slug);
}
